// export const cardData = [
//     { id: 1, value: '🐶' },
//     { id: 2, value: '🐱' },
//     { id: 3, value: '🐭' },
//     { id: 4, value: '🐹' },
//     { id: 5, value: '🐰' },
//     { id: 6, value: '🦊' },
//     { id: 7, value: '🐻' },
//     { id: 8, value: '🐼' },
//     { id: 9, value: '🐶' },
//     { id: 10, value: '🐱' },
//     { id: 11, value: '🐭' },
//     { id: 12, value: '🐹' },
//     { id: 13, value: '🐰' },
//     { id: 14, value: '🦊' },
//     { id: 15, value: '🐻' },
//     { id: 16, value: '🐼' }
//   ];
export const cardData = [
    {id:1, value: 'A'},
    {id:2, value: 'B'},
    {id:3, value: 'C'},
    {id:4, value: 'D'},
    {id:5, value: 'E'},
    {id:6, value: 'F'},
    {id:7, value: 'G'},
    {id:8, value: 'H'},
    {id:9, value: 'A'},
    {id:10, value: 'B'},
    {id:11, value: 'C'},
    {id:12, value: 'D'},
    {id:13, value: 'E'},
    {id:14, value: 'F'},
    {id:15, value: 'G'},
    {id:16, value: 'H'},
]